### ISSUE TITLE
Подскажите, как делать пулреквесты

### ISSUE THREAD

**Issue by Pesssimist** [mnaoumov/obsidian-community-vault#1]
Потихоньку буду наполнять заметки, может на несколько десятков меня хватит.
Но не получается сделать пуллреквест по причине отсутствия опыта.
Ну и просто для начала, несколько уже внесённых изменений, может такая работа не нужна никому, я и не буду заморачиваться.
![Advanced Tables_button](https://github.com/mnaoumov/obsidian-community-vault/assets/112248308/8ad53430-0007-4b49-b98b-2f3eab2bae87)
![Advanced Tables_right ribbon menu](https://github.com/mnaoumov/obsidian-community-vault/assets/112248308/f139532f-6a80-4fea-9014-8dc40eec0830)
[!.md](https://github.com/mnaoumov/obsidian-community-vault/files/13946827/default.md)
[Advanced Tables.md](https://github.com/mnaoumov/obsidian-community-vault/files/13946828/Advanced.Tables.md)
[Editing Toolbar.md](https://github.com/mnaoumov/obsidian-community-vault/files/13946829/Editing.Toolbar.md)

**Comment by mnaoumov** [comment]
@Pesssimist попробуйте инструкцию https://github.com/urfu-2015/guides/blob/master/how-to-pull-request.md

**Comment by Pesssimist** [comment]
> @Pesssimist попробуйте инструкцию https://github.com/urfu-2015/guides/blob/master/how-to-pull-request.md

Пока непонятно, в мобильной версии гитхаба кнопку форк не нашел, да и в вэбверсии она видна только в полной версии сайта для пк. В любом случае, это только дома получится сделать, там и проще и головняков нет.
Спасибо за инструкцию, буду пробовать приобщиться.
