### ISSUE TITLE
Требования к форматированию?

### ISSUE THREAD

**Issue by Pesssimist** [mnaoumov/obsidian-community-vault#6]
Может быть выскажете какие-то требования по форматированию?
Я по какому-то из Ваших файлов начал использовать `такой вид форматирования` для терминов и английских названий, может ещё что-то нужно учитывать?
Как человек, не работающий с кодом, я не знаю, какие есть требования для улучшения читаемости текста в том числе...

**Comment by mnaoumov** [comment]
Как сказано в `README` - нужно форматировать Linter'ом. Форматирование терминов вы сами поняли. Вроде других правил нет

**Comment by Pesssimist** [comment]
упс, я только после Вашего ответа увидел изменения в Readme, но проверил свои заметки, вроде линтер нигде ничего не изменил.
и ещё, у меня то есть свободное время, то нет, так что как Вам будет удобно, если я буду выкладывать какие-то изменения по возможности? или лучше "накопить" побольше правок и вбрасывать их пакетом?
а то и мысли скачут, да и времени нормально не хватает.

**Comment by mnaoumov** [comment]
Можете кидать частями
